# Generated by Django 5.2.1 on 2025-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customeuser_firstname_customeuser_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
