# Generated by Django 5.0.7 on 2025-05-12 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RBAC_API.role'),
        ),
    ]
