# Generated by Django 5.0.7 on 2025-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC_API', '0002_userpermission_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
